### ISSUE TITLE
FIx relative files paths in bin scripts

### ISSUE THREAD

**Issue by paulgroves** [BCGDV/lon-kinbal#13]
Currently, file paths fail when following the README and execution bin scripts from the root of the repo

e.g https://github.com/BCGDV/lon-kinbal/blob/main/bin/core/EKS/deploy.sh#L2

https://stackoverflow.com/questions/24112727/relative-paths-based-on-file-location-instead-of-current-working-directory

**Comment by ppanchal97** [comment]
Can reproduce, wip.

**Comment by ppanchal97** [comment]
@paulgroves I propose prepending `$(cd $(dirname "$1");pwd)/$(basename "$1")` to preserve the absolute path.
